site_name: GRASP Lab
site_url: http://grasp.famnit.upr.si

theme:
  name: material
  font:
    text: Inter Tight
    code: JetBrains Mono
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs # Top horizontal menu
    - navigation.sections # Sidebar groupings

nav:
  - Home: index.md
  - Research: research.md
  - Team: team.md

plugins:
  - search
  - bibtex:
      bib_file: "docs/publications.bib"

markdown_extensions:
  - footnotes

extra_css:
  - css/custom-theme.css