name: Deploy GRASP to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      # We must install the Pandoc system package first
      - name: Install Pandoc Dependency
        run: sudo apt-get update && sudo apt-get install -y pandoc
          
      # Install both the main theme and the bibtex extension
      - name: Install MkDocs and Plugins
        run: pip install mkdocs-material mkdocs-bibtex
        
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force