name: Deploy GRASP Webpage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install MkDocs and Material Theme
        run: pip install mkdocs-material
        
      - name: Compile Markdown to HTML
        run: mkdocs build

      # Copy files directly on the machine
      - name: Copy Files Locally
        run: cp -r site/* /var/www/grasp-lab/